version: 2
updates:
    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: monthly
      # Disable npm dep upgrades - will handle manually from now on
      open-pull-requests-limit: 0
